import Foundation

// ─────────────────────────────────────────────────────────────────────────────
//  SHARED SOURCE — compiled into both the app and the widget extension.
//
//  This file exists twice: here, and at ElemoraWidgets/Shared/ with identical
//  contents. `Tools/check_widget_shared.py` fails the build if the two ever
//  differ by a single byte.
//
//  Dates here use JSONCoder's default strategy on purpose. It writes
//  `timeIntervalSinceReferenceDate` straight out as a number, which is the
//  only strategy that survives a round trip exactly: ISO 8601 carries whole
//  seconds (milliseconds at best), and seconds-since-1970 adds and then
//  subtracts an epoch offset large enough to cost the low bits. A decoded
//  record that is merely close to the one written would break the ordering of
//  two taps in the same second, and would make "write it, read it, get it
//  back" a property that is nearly true.
//
//  Why a copy rather than one file in two targets: the project uses
//  file-system synchronized groups, where a folder belongs to a target. Two
//  targets sharing one folder is expressible but fragile to hand-maintain, and
//  a serialization contract that silently diverges between a widget and its
//  app is the exact bug this arrangement is meant to make impossible. A byte
//  comparison in CI is a stronger guarantee than a build setting.
// ─────────────────────────────────────────────────────────────────────────────

/// The container the app and its widget both write to.
enum ElemoraAppGroup {
    /// Registered against `com.idlery.periodicpro`.
    static let identifier = "group.com.idlery.periodicpro"

    /// The shared container, or `nil` when the App Group is unavailable.
    ///
    /// Nil is a real case and is handled everywhere rather than trapped: a
    /// build signed without the entitlement, or a simulator that has not been
    /// provisioned for it, returns nothing here. The app then falls back to
    /// its own container and simply has no widget data — which is a widget
    /// that shows a placeholder, not an app that crashes.
    static var containerURL: URL? {
        FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: identifier)
    }

    static var isAvailable: Bool { containerURL != nil }

    static func fileURL(_ name: String) -> URL? {
        containerURL?.appendingPathComponent(name, isDirectory: false)
    }
}

/// One question answered on the Home Screen.
///
/// The widget cannot write to the app's SwiftData store — it is a separate
/// process with its own lifetime, and two writers on one store is how a
/// learner's progress gets corrupted. So the widget appends an event, and the
/// app merges it when it next runs. The event carries its own identity, which
/// is what makes the merge idempotent: an intent that iOS retries, or a merge
/// that runs twice, cannot count an answer twice.
struct WidgetAnswerEvent: Codable, Hashable, Identifiable, Sendable {
    /// Unique per answer. Generated by the widget at the moment of the tap.
    let id: UUID
    /// The question that was asked, so a repeat of the same question on a
    /// later day is a separate event.
    let questionID: String
    /// What the answer was about: `element-26`, or a compound identifier.
    let subjectKey: String
    let isCorrect: Bool
    let answeredAt: Date
    /// Which difficulty it was, for the rank's depth term.
    let isAdvanced: Bool

    init(
        id: UUID = UUID(),
        questionID: String,
        subjectKey: String,
        isCorrect: Bool,
        answeredAt: Date = Date(),
        isAdvanced: Bool = false
    ) {
        self.id = id
        self.questionID = questionID
        self.subjectKey = subjectKey
        self.isCorrect = isCorrect
        self.answeredAt = answeredAt
        self.isAdvanced = isAdvanced
    }

    /// The atomic number this was about, when it was about an element.
    var atomicNumber: Int? {
        guard subjectKey.hasPrefix("element-") else { return nil }
        return Int(subjectKey.dropFirst("element-".count))
    }
}

/// What the widget draws without asking the app anything.
///
/// Written by the app on every foreground and after every merge. The widget
/// reads it and never computes it: a Home Screen timeline runs on its own
/// schedule in its own process, and recomputing mastery there would be both
/// slow and a second opinion about the same numbers.
struct WidgetProgressSnapshot: Codable, Hashable, Sendable {
    var masteredElements: Int = 0
    var totalElements: Int = 118
    var currentStreak: Int = 0
    var dueReviewCount: Int = 0
    var rankTitle: String = "Element Explorer"
    /// Questions the widget can ask, pre-built by the app so the widget never
    /// has to load the element catalog.
    var questions: [WidgetQuestion] = []
    var updatedAt: Date = .distantPast

    static let fileName = "widget-snapshot.json"
}

/// One question, ready to render.
struct WidgetQuestion: Codable, Hashable, Identifiable, Sendable {
    let id: String
    /// "Which element is Fe?"
    let prompt: String
    let options: [String]
    let correctIndex: Int
    /// What it is about, for the answer event.
    let subjectKey: String
    /// A line shown after answering: the fact behind it.
    let detail: String

    func isCorrect(_ index: Int) -> Bool { index == correctIndex }
    var correctAnswer: String { options.indices.contains(correctIndex) ? options[correctIndex] : "" }
}

/// The append-only log the widget writes and the app drains.
///
/// A file rather than `UserDefaults`: two processes writing the same defaults
/// key race, and the loser's write is simply gone. Each event is one line of
/// JSON, appended, so two writers at once interleave whole lines rather than
/// corrupting a single document — and the app's merge is keyed on the event's
/// own identifier, so even a duplicated line counts once.
struct WidgetEventLog: Sendable {
    static let fileName = "widget-events.jsonl"
    /// Past this the oldest are dropped. A learner who somehow answered ten
    /// thousand widget questions without opening the app is not a case worth
    /// growing a file without bound for.
    static let maximumEvents = 2_000

    let url: URL?

    init(url: URL? = ElemoraAppGroup.fileURL(WidgetEventLog.fileName)) {
        self.url = url
    }

    var isAvailable: Bool { url != nil }

    /// Appends one event. Silent when there is no shared container — the
    /// widget still shows the right answer, the app simply never learns of it.
    func append(_ event: WidgetAnswerEvent) {
        guard let url, let line = Self.encode(event) else { return }
        let data = Data((line + "\n").utf8)
        if let handle = try? FileHandle(forWritingTo: url) {
            defer { try? handle.close() }
            _ = try? handle.seekToEnd()
            try? handle.write(contentsOf: data)
        } else {
            try? data.write(to: url, options: .atomic)
        }
    }

    /// Everything written so far, oldest first, with unreadable lines skipped
    /// rather than allowed to stop the merge.
    func read() -> [WidgetAnswerEvent] {
        guard let url, let text = try? String(contentsOf: url, encoding: .utf8) else { return [] }
        let decoder = JSONDecoder()
        var found: [WidgetAnswerEvent] = []
        for line in text.split(separator: "\n") {
            guard let data = line.data(using: .utf8),
                  let event = try? decoder.decode(WidgetAnswerEvent.self, from: data) else { continue }
            found.append(event)
        }
        if found.count > Self.maximumEvents {
            found = Array(found.suffix(Self.maximumEvents))
        }
        return found
    }

    /// Empties the log. Called by the app only after the events have been
    /// merged and saved, so a crash between the two loses nothing: the events
    /// are still there and merging them again is a no-op.
    func clear() {
        guard let url else { return }
        try? Data().write(to: url, options: .atomic)
    }

    static func encode(_ event: WidgetAnswerEvent) -> String? {
        let encoder = JSONEncoder()
        guard let data = try? encoder.encode(event) else { return nil }
        return String(data: data, encoding: .utf8)
    }
}

/// Reads and writes the snapshot the widget renders.
struct WidgetSnapshotStore: Sendable {
    let url: URL?

    init(url: URL? = ElemoraAppGroup.fileURL(WidgetProgressSnapshot.fileName)) {
        self.url = url
    }

    func read() -> WidgetProgressSnapshot? {
        guard let url, let data = try? Data(contentsOf: url) else { return nil }
        let decoder = JSONDecoder()
        return try? decoder.decode(WidgetProgressSnapshot.self, from: data)
    }

    func write(_ snapshot: WidgetProgressSnapshot) {
        guard let url else { return }
        let encoder = JSONEncoder()
        guard let data = try? encoder.encode(snapshot) else { return }
        try? data.write(to: url, options: .atomic)
    }
}

/// What the widget itself remembers between redraws.
///
/// Separate from the event log, and never cleared by the app, because the two
/// answer different questions. The log is "what has the app not counted yet";
/// this is "which of today's questions has this Home Screen already asked".
/// Folding them together would mean that the moment the app drained the log,
/// the widget would forget it had asked anything and ask the same question
/// again.
///
/// It is keyed on question identifiers, which carry the day they were built
/// for. When the app publishes a new day's snapshot, none of yesterday's
/// identifiers match and the widget starts at the first question again,
/// without anything having to expire it.
struct WidgetInteractionState: Codable, Hashable, Sendable {
    /// Questions already asked and answered, oldest first.
    var answeredQuestionIDs: [String] = []
    /// The answer still being shown, if one is. Cleared by tapping Next,
    /// which is what advances the widget to the following question.
    var revealedQuestionID: String?
    var revealedChoice: Int?
    var revealedWasCorrect: Bool?
    var revealedAt: Date?

    static let fileName = "widget-state.json"
    /// Enough for a long day of tapping; bounded so the file cannot grow.
    static let historyLimit = 64

    func hasAnswered(_ questionID: String) -> Bool {
        answeredQuestionIDs.contains(questionID)
    }

    /// The question the widget should show next: the first of the snapshot's
    /// questions that has not been answered. `nil` once they are all done,
    /// which the widget renders as a finished state rather than by repeating
    /// itself.
    func nextQuestion(in snapshot: WidgetProgressSnapshot) -> WidgetQuestion? {
        snapshot.questions.first { !hasAnswered($0.id) }
    }

    /// The question whose result is on screen, if any.
    func revealedQuestion(in snapshot: WidgetProgressSnapshot) -> WidgetQuestion? {
        guard let revealedQuestionID else { return nil }
        return snapshot.questions.first { $0.id == revealedQuestionID }
    }

    mutating func record(
        questionID: String, choice: Int, isCorrect: Bool, at date: Date = Date()
    ) {
        if !answeredQuestionIDs.contains(questionID) {
            answeredQuestionIDs.append(questionID)
            if answeredQuestionIDs.count > Self.historyLimit {
                answeredQuestionIDs.removeFirst(answeredQuestionIDs.count - Self.historyLimit)
            }
        }
        revealedQuestionID = questionID
        revealedChoice = choice
        revealedWasCorrect = isCorrect
        revealedAt = date
    }

    mutating func dismissReveal() {
        revealedQuestionID = nil
        revealedChoice = nil
        revealedWasCorrect = nil
        revealedAt = nil
    }
}

/// Reads and writes the widget's own state.
struct WidgetStateStore: Sendable {
    let url: URL?

    init(url: URL? = ElemoraAppGroup.fileURL(WidgetInteractionState.fileName)) {
        self.url = url
    }

    func read() -> WidgetInteractionState {
        guard let url, let data = try? Data(contentsOf: url) else { return WidgetInteractionState() }
        let decoder = JSONDecoder()
        return (try? decoder.decode(WidgetInteractionState.self, from: data))
            ?? WidgetInteractionState()
    }

    func write(_ state: WidgetInteractionState) {
        guard let url else { return }
        let encoder = JSONEncoder()
        guard let data = try? encoder.encode(state) else { return }
        try? data.write(to: url, options: .atomic)
    }
}
