import Foundation

/// The constants advanced questions are computed from.
///
/// Both are exact by definition rather than measured: since the 2019 SI
/// redefinition the Avogadro constant is a fixed number, and the molar mass
/// constant is derived from it. Nothing here is a rounded textbook value.
enum ChemicalConstants {
    /// Exact, by the 2019 SI definition of the mole.
    static let avogadro = 6.022_140_76e23
    /// The atomic weights come from IUPAC 2021, through `elements.json`.
    static let atomicWeightSource = "IUPAC 2021 standard atomic weights"
}

/// One step of a worked solution.
///
/// Answering wrongly and being told only "wrong" teaches nothing, so every
/// advanced question carries the arithmetic that produced its answer, in the
/// order a person would write it.
struct SolutionStep: Equatable, Hashable, Sendable {
    /// What this step is doing — "Add the atomic weights".
    let label: String
    /// The arithmetic itself — "2(1.008) + 32.06 + 4(15.999)".
    let expression: String
}

/// What counts as answering an advanced question.
enum AdvancedAnswer: Equatable, Hashable, Sendable {
    /// Pick one.
    case choice(options: [String], correctIndex: Int)
    /// Type a number. `tolerance` is relative, so the grading follows the
    /// precision of the value rather than a fixed number of decimal places.
    case numeric(value: Double, unit: String, tolerance: Double)

    /// The tolerance a calculation question uses unless it says otherwise.
    ///
    /// One percent. Wide enough that rounding the atomic weights on the way —
    /// which is what a learner with a periodic table in front of them will do
    /// — is never marked wrong, and narrow enough that a wrong method is.
    /// Significant figures are not graded here: a question that is *about*
    /// significant figures would say so and set its own tolerance.
    static let defaultTolerance = 0.01

    var correctText: String {
        switch self {
        case .choice(let options, let index): return options[index]
        case .numeric(let value, let unit, _):
            return unit.isEmpty ? Self.format(value) : "\(Self.format(value)) \(unit)"
        }
    }

    /// Whether a typed or chosen answer is right.
    func accepts(_ response: String) -> Bool {
        switch self {
        case .choice(let options, let index):
            guard let chosen = options.firstIndex(where: {
                $0.compare(response, options: [.caseInsensitive, .diacriticInsensitive]) == .orderedSame
            }) else { return false }
            return chosen == index
        case .numeric(let value, _, let tolerance):
            guard let given = Self.parse(response) else { return false }
            // A relative window, with an absolute floor so an answer of zero
            // is not compared against a window of zero width.
            let window = max(abs(value) * tolerance, 1e-9)
            return abs(given - value) <= window
        }
    }

    func accepts(index: Int) -> Bool {
        guard case .choice(_, let correct) = self else { return false }
        return index == correct
    }

    /// Reads what a learner typed, including the ways they write a power of
    /// ten: `1.5e23`, `1.5E23`, `1.5 x 10^23`, `1.5 × 10^23`.
    static func parse(_ text: String) -> Double? {
        var cleaned = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: ",", with: "")
            .replacingOccurrences(of: " ", with: "")
        guard !cleaned.isEmpty, cleaned.count <= 40 else { return nil }
        for marker in ["×10^", "x10^", "X10^", "*10^", "×10", "x10", "X10", "*10"] {
            if let range = cleaned.range(of: marker) {
                cleaned.replaceSubrange(range, with: "e")
                break
            }
        }
        cleaned = cleaned.replacingOccurrences(of: "^", with: "")
        return Double(cleaned)
    }

    /// Enough digits to be exact without being unreadable.
    static func format(_ value: Double) -> String {
        let magnitude = abs(value)
        if magnitude != 0, magnitude < 0.001 || magnitude >= 1e6 {
            return String(format: "%.3e", value)
        }
        let rounded = (value * 1_000).rounded() / 1_000
        if rounded == rounded.rounded() && abs(rounded) < 1e6 {
            return String(Int(rounded))
        }
        return String(format: "%g", rounded)
    }
}

/// One advanced chemistry question.
///
/// Every one of these is computed from data the app already ships and can
/// cite: IUPAC 2021 atomic weights, the electron configurations in
/// `elements.json`, the curated compounds in `compounds.json`, and the two
/// exact SI constants above. Nothing is generated by a language model, and
/// nothing is generated at runtime from a template with a number invented to
/// fill it — the numbers are the answer, worked out.
struct AdvancedQuestion: Identifiable, Equatable, Hashable, Sendable {
    enum Kind: String, CaseIterable, Codable, Hashable, Sendable {
        case molarMass
        case percentComposition
        case molesToParticles
        case massToMoles
        case empiricalFormula
        case electronConfiguration
        case valenceElectrons
        case electronegativityComparison
        case sharedProperty
        case ionicCharge
        case oxidationState
        case formulaForName

        var title: String {
            switch self {
            case .molarMass: return "Molar mass"
            case .percentComposition: return "Percent composition"
            case .molesToParticles: return "Moles to particles"
            case .massToMoles: return "Mass to moles"
            case .empiricalFormula: return "Empirical formula"
            case .electronConfiguration: return "Electron configuration"
            case .valenceElectrons: return "Valence electrons"
            case .electronegativityComparison: return "Periodic trends"
            case .sharedProperty: return "Groups and periods"
            case .ionicCharge: return "Ionic charge"
            case .oxidationState: return "Oxidation state"
            case .formulaForName: return "Writing a formula"
            }
        }

        /// Whether answering means typing a number rather than picking.
        var isCalculation: Bool {
            switch self {
            case .molarMass, .percentComposition, .molesToParticles, .massToMoles, .valenceElectrons:
                return true
            default:
                return false
            }
        }
    }

    let id: Int
    let kind: Kind
    let subject: QuizSubject
    let prompt: String
    let answer: AdvancedAnswer
    /// The arithmetic, shown after answering either way.
    let solution: [SolutionStep]
    /// Where the numbers came from.
    let sourceNote: String

    var isCalculation: Bool { kind.isCalculation }
}
